@extends('admin.layout')
@section('title','Orders')
@section('header','Daftar Pesanan')
@section('content')
<div class="flex justify-between items-center mb-6"><p class="text-sm" style="color:rgba(245,237,216,.4)"><?php echo e($orders->total()); ?> pesanan</p></div>
@if(session('success'))<div class="text-sm px-4 py-3 rounded-xl mb-4" style="background:rgba(201,168,76,.15);border:1px solid rgba(201,168,76,.3);color:#6BAED6"><?php echo e(session('success')); ?></div>@endif
<div class="rounded-2xl overflow-hidden" style="background:rgba(255,255,255,.03);border:1px solid rgba(245,237,216,.08)"><table class="w-full text-sm"><thead><tr style="border-bottom:1px solid rgba(245,237,216,.07)"><th class="px-4 py-3 text-left text-[10px] tracking-[.2em] uppercase font-semibold" style="color:rgba(245,237,216,.3)">No Pesanan</th><th class="px-4 py-3 text-left text-[10px] tracking-[.2em] uppercase font-semibold" style="color:rgba(245,237,216,.3)">Pelanggan</th><th class="px-4 py-3 text-left text-[10px] tracking-[.2em] uppercase font-semibold hidden md:table-cell" style="color:rgba(245,237,216,.3)">Total</th><th class="px-4 py-3 text-left text-[10px] tracking-[.2em] uppercase font-semibold">Status</th><th class="px-4 py-3 text-left text-[10px] tracking-[.2em] uppercase font-semibold hidden md:table-cell">Tanggal</th><th class="px-4 py-3"></th></tr></thead><tbody>
@forelse($orders as $order)
@php $statusMap=['pending'=>['Baru','rgba(201,168,76,.15)','#C9A84C'],'dikonfirmasi'=>['Diproses','rgba(96,165,250,.15)','#60a5fa'],'dikemas'=>['Dikemas','rgba(192,132,252,.15)','#c084fc'],'diantar'=>['Dikirim','rgba(99,102,241,.15)','#818cf8'],'selesai'=>['Selesai','rgba(74,222,128,.15)','#4ade80'],'dibatalkan'=>['Dibatalkan','rgba(248,113,113,.15)','#f87171']]; $s=$statusMap[$order->status]??$statusMap['pending']; @endphp
<tr class="hover:bg-white/5 transition" style="border-bottom:1px solid rgba(245,237,216,.05)"><td class="px-4 py-3 font-mono text-xs" style="color:rgba(245,237,216,.55)"><?php echo e($order->order_number ?? ('GBN-' . $order->created_at->format('Ymd') . '-' . str_pad($order->id, 4, '0', STR_PAD_LEFT))); ?></td><td class="px-4 py-3 font-medium" style="color:#D8E4ED"><?php echo e($order->full_name); ?><br>@if($order->email)<span style="font-size:11px;color:rgba(216,228,237,.35)"><?php echo e($order->email); ?></span>@endif</td><td class="px-4 py-3 font-semibold hidden md:table-cell" style="color:#6BAED6">Rp <?php echo e(number_format($order->total,0,',','.')); ?></td><td class="px-4 py-3"><span class="px-2.5 py-1 rounded-full text-[10px] font-bold" style="background:<?php echo e($s[1]); ?>;color:<?php echo e($s[2]); ?>"><?php echo e($s[0]); ?></span></td><td class="px-4 py-3 text-xs hidden md:table-cell" style="color:rgba(245,237,216,.3)"><?php echo e($order->created_at->format('d M Y H:i')); ?></td><td class="px-4 py-3"><a href="<?php echo e(route('admin.orders.show',$order)); ?>" class="text-xs font-semibold hover:underline" style="color:#6BAED6">Detail &rarr;</a></td></tr>
@empty<tr><td colspan="6" class="px-4 py-12 text-center" style="color:rgba(245,237,216,.3)">Belum ada pesanan.</td></tr>@endforelse
</tbody></table></div><div class="mt-4"><?php echo e($orders->links()); ?></div>
@endsection
